services:
  - type: web
    name: minio-storage
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: MINIO_ROOT_USER
        value: Anmol
      - key: MINIO_ROOT_PASSWORD
        value: Molan@#123
      - key: PORT
        value: 9000